import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Upload, Sparkles, Copy, Download, Check } from 'lucide-react';

const AISummarizer = () => {
  const [inputText, setInputText] = useState('');
  const [summary, setSummary] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [file, setFile] = useState<File | null>(null);

  const handleGenerateSummary = async () => {
    if (!inputText.trim() && !file) return;
    
    setIsGenerating(true);
    
    // Simulate API call
    setTimeout(() => {
      setSummary(`This is a simulated summary of your content. In a real application, this would be generated by an AI model based on your input: "${inputText.substring(0, 50)}..."`);
      setIsGenerating(false);
    }, 2000);
  };

  const handleCopySummary = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadSummary = () => {
    const element = document.createElement('a');
    const file = new Blob([summary], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'summary.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      // In a real app, you would process the file content here
      setInputText(`Content from ${e.target.files[0].name} will be summarized...`);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-8"
        >
          <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Summarizer</h1>
          <p className="text-lg text-gray-600">
            Transform lengthy documents into concise summaries with AI
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Section */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="bg-white rounded-2xl p-6 shadow-lg"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Input Content</h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Paste your text or upload a document
                </label>
                <textarea
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  rows={8}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                  placeholder="Paste your article, research paper, or any lengthy text here..."
                />
              </div>
              
              <div className="relative">
                <input
                  type="file"
                  onChange={handleFileUpload}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  accept=".txt,.pdf,.doc,.docx"
                />
                <div className="flex items-center justify-center px-4 py-3 border-2 border-dashed border-gray-300 rounded-xl hover:border-blue-400 transition-colors">
                  <Upload className="h-5 w-5 text-gray-400 mr-2" />
                  <span className="text-gray-600">
                    {file ? file.name : 'Upload a document (PDF, DOC, TXT)'}
                  </span>
                </div>
              </div>
              
              <button
                onClick={handleGenerateSummary}
                disabled={isGenerating || (!inputText.trim() && !file)}
                className="w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:from-gray-400 disabled:to-gray-500 text-white font-medium py-3 px-6 rounded-xl transition-all transform hover:scale-105 disabled:scale-100 disabled:cursor-not-allowed flex items-center justify-center"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                    Generating Summary...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-5 w-5 mr-2" />
                    Generate AI Summary
                  </>
                )}
              </button>
            </div>
          </motion.div>

          {/* Output Section */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="bg-white rounded-2xl p-6 shadow-lg"
          >
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-semibold text-gray-900">AI Summary</h2>
              {summary && (
                <div className="flex space-x-2">
                  <button
                    onClick={handleCopySummary}
                    className="p-2 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                    title="Copy to clipboard"
                  >
                    {copied ? <Check className="h-5 w-5 text-green-600" /> : <Copy className="h-5 w-5" />}
                  </button>
                  <button
                    onClick={handleDownloadSummary}
                    className="p-2 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                    title="Download summary"
                  >
                    <Download className="h-5 w-5" />
                  </button>
                </div>
              )}
            </div>
            
            <div className="min-h-[200px]">
              {summary ? (
                <div className="prose max-w-none">
                  <p className="text-gray-700 leading-relaxed">{summary}</p>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center h-64 text-center text-gray-500">
                  <FileText className="h-12 w-12 mb-4 text-gray-300" />
                  <p className="text-lg mb-2">Your AI-generated summary will appear here</p>
                  <p className="text-sm">Enter content and click "Generate AI Summary" to get started</p>
                </div>
              )}
            </div>
            
            {summary && (
              <div className="mt-6 p-4 bg-gradient-to-r from-blue-500 to-purple-600 rounded-xl text-white">
                <div className="flex items-start space-x-3">
                  <Sparkles className="h-5 w-5 mt-0.5 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-sm">AI Tip</h4>
                    <p className="text-sm text-blue-100">
                      Try adjusting the length or focus of your summary by specifying key points you want to emphasize.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        </div>

        {/* Features Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-8 bg-white rounded-2xl p-6 shadow-lg"
        >
          <h2 className="text-xl font-semibold text-gray-900 mb-6">How It Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mx-auto mb-4">
                <FileText className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">1. Input Content</h3>
              <p className="text-gray-600 text-sm">
                Paste your text or upload a document that you want to summarize
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mx-auto mb-4">
                <Sparkles className="h-6 w-6 text-purple-600" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">2. AI Processing</h3>
              <p className="text-gray-600 text-sm">
                Our advanced AI analyzes your content and extracts key points
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-green-100 rounded-xl flex items-center justify-center mx-auto mb-4">
                <Check className="h-6 w-6 text-green-600" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">3. Get Summary</h3>
              <p className="text-gray-600 text-sm">
                Receive a concise, accurate summary that captures the essence
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default AISummarizer;